<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-02J8MEC" failures="1" tests="7" name="C:/Users/acer/IdeaProjects/MavenProject/src/test/java" time="0.074" errors="0" timestamp="2025-07-04T15:35:19 IST">
  <testcase classname="TestNgProject.TestNG.FailedTestCaseExample" name="Test1" time="0.006"/>
  <testcase classname="TestNgProject.TestNG.FailedTestCaseExample" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNgProject.TestNG.FailedTestCaseExample" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNgProject.TestNG.FailedTestCaseExample" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNgProject.TestNG.FailedTestCaseExample" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNgProject.TestNG.FailedTestCaseExample" name="Test2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNgProject.TestNG.FailedTestCaseExample.Test2(FailedTestCaseExample.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNgProject.TestNG.FailedTestCaseExample" name="Test3" time="0.001"/>
</testsuite> <!-- C:/Users/acer/IdeaProjects/MavenProject/src/test/java -->
